### ISSUE TITLE
Update rxjava-gwt to 2.2.2-gwt2

### ISSUE THREAD

**Issue by TDesjardins** [intendia-oss/autorest#14]
Some things are fixed since release of **rxjava-gwt 2.1.2-beta1**. For example a possible NPE when not setting `UncaughtExceptionHandler`. Does it make sense to update this dependency?

What is the logic behind the tags `xxx-gwtx` and `x.x.x-betax`?

**Comment by ibaca** [comment]
GWT version and RxJava version must be kept in sync, but I'll definitively update to the last version so you can upgrade to 2.2.8. I'll try this weekend. 👍

**Comment by ibaca** [comment]
@TDesjardins eh, but the last RxJava GWT version was 2.2.2-gwt2, so the fix was already applied. You can use AutoREST with any RxJava2 version, usually the last one. Also, I just released RxJava GWT 2.2.10-gwt1 if you want to move directly to that, also including a GwtScheduler fix that caused some delayed operator to emmit an event after it was disposed.

The logic behind gwtX and betaX; I thought that people will scary a bit more if the dependency includes beta, so after more than 2 years of using it in production we changed it from beta to gwt suffix. Releases use the same version than RxJava, so if there is any bug I need to release it with the same version number and I add the +1 to the suffix. So, you must always use the last published subversion, the last gwtX version (aka the hotfix number).

**Comment by TDesjardins** [comment]
Thanks @ibaca !
