### ISSUE TITLE
Streaming response with Observable

### ISSUE THREAD

**Issue by frami** [intendia-oss/autorest#2]
Thank you for the great work! I used before RestyGWT, but Autorest is a great new solution. 

I try to stream a search result from the server to the client.  On the server side I use the StreamingOutput from Jaxrs. On the client I tried to work with Observable and get every result with onNext(...). But the onNext() Method is not called until the hole response is received.

Is there a way to get a stream of results?

Best regards
Michael

**Comment by ibaca** [comment]
Might be... although this is a pretty cool and interesting use case, I think that in practice is not quite important for typical applications. Anyway, if this is possible add it to some of the autorest samples will be awesome. How do you read (in streaming mode) this kind of streaming responses in JS? (this is the first thing to solve to see how to integrate in GWT).

**Comment by ibaca** [comment]
I have been investigating how responses can be readed in streaming mode. And I think that standard XmlHttpRequest responses can be readed at once at finish (standard case), or can be readed in modern browsers using the progress event. With this event you can read multiple time the whole text, which get incremented in each notification, this "might be useful" but if you need to parse the json response, this is even more complicated because you need a custom parsing to allow partial json decoding. This is a pretty poor strategy to implement streaming responses, although in some cases might be useful, doesn't look very useful in general.

Later on, I started investigating SSE and I have created this mini project to see how it can be integrated and how it works https://github.com/ibaca/autorest-streaming-example. This looks more easy to integrate, and more useful in general.

Anyway, some kind of simplification of the first problem might be much easier to implement, specially if you send data in lines, or some kind of easy to split encoding. If you are interested, I recommend that you create a similar project than autorest-streaming-example, and customize the XhrResourceBuilder to support some custom progressive decoding format.

**Comment by frami** [comment]
Thank you very much for your investigation. I will try to implement my result streaming according your example. After that I will give you a feedback about it.

**Comment by ibaca** [comment]
I'm going to close this. This is interesting, I'm still making some updates to the autorest-streaming-example...  but I'm not sure how to integrate this in the server side.
