### ISSUE TITLE
@Consumes is ignored

### ISSUE THREAD

**Issue by alesp** [intendia-oss/autorest#9]
I have an interface with a method, marked with @Consumes(MediaType.APPLICATION_FORM_URLENCODED), which has parameters marked with @FormParam. Something like this:

```
@AutoRestGwt
@Path("v1")
public interface JsonService {
	@POST
	@Path("update")
	@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
	@Produces(MediaType.APPLICATION_JSON)
	Single<String> update(@FormParam("lang") String lang);
}
```

Although annotation processor creates class with ...consume("application/x-www-urlencoded")..., this value is later ignored.

Autorest should set Content-type: application/x-www-urlencoded when calling the server. It actually sets Content-type to "application/json".

**Comment by ibaca** [comment]
Yep, you are right, it ignores it. But it is on purpose because form_urlencoded is not implemented in `RequestResourceBuilder`. We really encourage to always use JSON so the implementation keeps simple. For example, you can expose this service and add `@GwtIncompatible`, and create the same endpoint but use JSON, so, for example, create a `updateFrom` and `updateJson`. It is trivial to implement. If you have some static page with a login form it can be used, and in your GWT app, you use the JSON variant instead.

🤔 uhm... but yep, consumes text or urlencoded can be mapped to `String`. Although this makes this interface not compatible with the server side (which looks like you are not using).

If you really want to use urlencoded, for example, because the server is out of your control. You need to improve the `RequestResourceBuilder`. to detect and support this format. Here there is a reference implementation, although it still uses rxjava1. I'll try to update, maybe I even remove the gwt-user dependency and only use elemental2 in the `RequestResourceBuilder`.
https://github.com/intendia-oss/autorest/blob/gwt-jsinterop/gwt/src/main/java/com/intendia/gwt/autorest/client/XhrResourceBuilder.java#L143

In general, I strongly recommend creating your own `ResourceBuilder` in each project, actually per user or company. I mean, the whole point of `AutoREST` is that mapping your REST interface to any `request builder utility` is much easier, you can even use the modern `JS fetch API` which is even easier and fits perfectly with RxJava ([use this](https://github.com/intendia-oss/rxgwt/blob/2.x/core/src/main/java/com/intendia/rxgwt2/elemental2/RxElemental2.java#L29) 😉).

If you try to implement your self (strongly recommended!) you can ask any question here or in Gitter (both GWT or AutoREST channels).

**Comment by alesp** [comment]
I'll try to do something as you suggested. Thank you for all the information.

**Comment by ibaca** [comment]
I'm going to close this because `@Consumes` it is now collected in `CollectorResourceVisitor`.
